name: "coronaviruses"

clustal:
  options: "--verbose --outfmt=clustal"

genomes:
  sarscov2: # SARS CoV 2
    filename: "GCF_009858895.2_ASM985889v3_genomic.fna"
    refseq-accession: "GCF_009858895.2"
  sars1: # Original SARS coronavirus
    filename: "GCF_000864885.1_ViralProj15500_genomic.fna"
    refseq-accession: "GCF_000864885.1"
