name: opentope
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  # Specialized software
  - clustalo=1.2.3
  - entrez-direct=13.3
  # R
  - r-base=3.6.1
  - r-systemfonts=0.1.1
  # Snakemake + Python
  - graphviz=2.40.1
  - python=3.7.3
  - snakemake=5.4.5
  # General utilities
  - pigz=2.4
  - wget=1.20.1
